import 'anime.dart';

const bookList = [
  Book(
    title: '1984',
    description: 'Антиутопия о тоталитарном обществе, где государство контролирует каждую мысль человека.',
    genre: 'Антиутопия, Политика',
    year: 1949,
    rating: 9.2,
    imagePath: 'assets/images/book1.jpg',
    author: 'Джордж Оруэлл',
  ),
  Book(
    title: 'Мастер и Маргарита',
    description: 'Дьявол приезжает в советскую Москву и устраивает хаос, переплетая судьбы людей с историей Пилата.',
    genre: 'Фантастика, Сатира',
    year: 1967,
    rating: 9.4,
    imagePath: 'assets/images/book2.jpg',
    author: 'Михаил Булгаков',
  ),
  Book(
    title: 'Гарри Поттер и философский камень',
    description: 'Мальчик-сирота узнаёт, что он волшебник, и поступает в школу магии Хогвартс.',
    genre: 'Фэнтези, Приключения',
    year: 1997,
    rating: 8.9,
    imagePath: 'assets/images/book3.jpg',
    author: 'Дж. К. Роулинг',
  ),
  Book(
    title: 'Преступление и наказание',
    description: 'Студент совершает убийство и мучается угрызениями совести, пока следователь ведёт расследование.',
    genre: 'Психологический роман',
    year: 1866,
    rating: 9.1,
    imagePath: 'assets/images/book4.jpg',
    author: 'Фёдор Достоевский',
  ),
  Book(
    title: 'Маленький принц',
    description: 'Философская сказка о маленьком принце, путешествующем по планетам в поисках смысла жизни.',
    genre: 'Сказка, Философия',
    year: 1943,
    rating: 9.0,
    imagePath: 'assets/images/book5.jpg',
    author: 'Антуан де Сент-Экзюпери',
  ),
  Book(
    title: 'Властелин колец',
    description: 'Хоббит и его товарищи отправляются в опасный поход, чтобы уничтожить кольцо всевластия.',
    genre: 'Фэнтези, Эпос',
    year: 1954,
    rating: 9.3,
    imagePath: 'assets/images/book6.jpg',
    author: 'Дж. Р. Р. Толкин',
  ),
  Book(
    title: 'Три товарища',
    description: 'История дружбы трёх молодых людей и трагической любви в послевоенной Германии.',
    genre: 'Роман, Драма',
    year: 1936,
    rating: 8.8,
    imagePath: 'assets/images/book7.jpg',
    author: 'Эрих Мария Ремарк',
  ),
  Book(
    title: 'Дюна',
    description: 'На пустынной планете разворачивается борьба за власть над ценнейшим ресурсом вселенной.',
    genre: 'Sci-Fi, Эпос',
    year: 1965,
    rating: 9.0,
    imagePath: 'assets/images/book8.jpg',
    author: 'Фрэнк Герберт',
  ),
  Book(
    title: 'Над пропастью во ржи',
    description: 'Подросток сбегает из школы и бродит по Нью-Йорку, размышляя о лицемерии взрослого мира.',
    genre: 'Роман, Молодёжная проза',
    year: 1951,
    rating: 8.6,
    imagePath: 'assets/images/book9.jpg',
    author: 'Джером Сэлинджер',
  ),
  Book(
    title: 'Граф Монте-Кристо',
    description: 'Моряк, несправедливо заключённый в тюрьму, выбирается на свободу и строит изощрённую месть.',
    genre: 'Приключения, Драма',
    year: 1844,
    rating: 9.2,
    imagePath: 'assets/images/book10.jpg',
    author: 'Александр Дюма',
  ),
];